---
casks:
  aerospace:
  caffeine:
  firefox:
  goland:
  google-chrome:
  iina:
  iterm2:
  karabiner-elements:
  libreoffice:
  lunar:
  macpass:
  moneymoney:
  orcaslicer:
  plex:
  sanesidebuttons:
  secretive:
  slack:
  spotify:
  steam:
  the-unarchiver:
  transmission:
  tunnelblick:
  utm:
  visual-studio-code:
  wireshark-app:
  zed:
  # Quick Look plugins
  apparency:
  qlcolorcode:
  qlimagesize:
  qlmarkdown:
  qlstephen:
  qlvideo:
  quicklook-json:
