---
pacman:
  # CLI
  ack:
  adobe-source-code-pro-fonts:
  ansible:
  archey3:
  aspell-de:
  aspell-en:
  axel:
  bash-completion:
  bash:
  bat:
  binwalk:
  coreutils:
  cowsay:
  cups:
  ddrescue:
  dialog:
  exa:
  fd:
  findutils:
  fish:
  fzf:
  gnome-keyring:
  gnu-netcat:
  go:
  grc:
  grep:
  htop:
  httpie:
  hub:
  hydra:
  iftop:
  iw:
  libsecret:
  mlocate:
  moreutils:
  mtr:
  ncdu:
  net-tools:
  nmap:
  numlockx:
  openssh:
  openssl:
  p7zip:
  pkgfile:
  pkgstats:
  pulseaudio-alsa:
  pwgen:
  python:
  redshift:
  rsync:
  ruby:
  shellcheck:
  smartmontools:
  speedtest-cli:
  sysstat:
  tcpdump:
  tmux:
  tree:
  ttf-dejavu:
  ttf-ionicons:
  ttf-ubuntu-font-family:
  unp:
  unrar:
  util-linux:
  vim:
  vte3-ng:
  wget:
  youtube-dl:
  zsh:

  # GUI
  arandr:
  arc-gtk-theme:
  arc-icon-theme:
  chromium:
  compton:
  dmenu:
  feh:
  firefox:
  gdm:
  gitg:
  gnome-extra:
  gnome-icon-theme:
  gnome-search-tool:
  gnome:
  i3-wm:
  i3status:
  i3blocks:
  libreoffice-fresh:
  lxappearance:
  nautilus:
  pavucontrol:
  riot-desktop:
  seahorse:
  sushi:
  terminator:
  termite:
  thunar-archive-plugin:
  thunar-media-tags-plugin:
  thunar-volman:
  thunar:
  transmission-gtk:
  vlc:
  wireshark-gtk:
  xorg-server:
  xorg-xinit:
